CREATE DATABASE gooseplan;

CREATE TABLE users(
    id BIGSERIAL PRIMARY KEY NOT NULL,
    name VARCHAR(200) NOT NULL,
    password VARCHAR(200) NOT NULL,
    UNIQUE(name)
);

CREATE TABLE todos(
    todo_id BIGSERIAL PRIMARY KEY NOT NULL,
    name VARCHAR(200) NOT NULL,
    title VARCHAR(200) NOT NULL,
    course VARCHAR(20),
    date VARCHAR(20),
    time VARCHAR(20),
    is_done INTEGER DEFAULT 0
);